#!/bin/bash

# trello branch
UT_TEAM="pi"

trello_branch_name() {
  if [ ! -n "${UT_TEAM}" ]; then
    echo "\$UT_TEAM not set!" && return 1;
  fi

  project=$1
  url=$2

  if [[ $url = '' ]]; then
    url=$project
    project=''
  fi

  if [[ $project != '' ]]; then
    project="--${project}"
  fi

  cardid=`echo $url | cut -d/ -f5`;
  description=`echo $url | cut -d/ -f6 | sed -e 's/-$//g' | sed -E 's/^[[:digit:]-]+//g'`;
  echo "${UT_TEAM}${project}--${cardid}--${description}";
}

trello_branch () {
  git checkout -b `trello_branch_name $1 $2`
}

open_branch () {
  git checkout `trello_branch_name $1 $2`
}
