#!/bin/bash

#
# vim
#

# vimrc
rm ~/.vimrc
ln -s ~/.dot-files/.vimrc ~/.vimrc

# vim directory
rm -rf ~/.vim
ln -s ~/.dot-files/.vim ~/.vim


#
# git
#

# git colors in various git commands
git config --global color.ui true

# global git ignore
rm ~/.gitignore_global
ln -s ~/.dot-files/.gitignore_global ~/.gitignore_global

# git autocomplete
curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash

# global git config
rm ~/.gitconfig
ln -s ~/.dot-files/.gitconfig ~/.gitconfig


#
# bash
#

# bash profile
rm ~/.bash_profile
ln -s ~/.dot-files/.bash_profile ~/.bash_profile

# bash history file
rm ~/.inputrc
ln -s ~/.dot-files/inputrc ~/.inputrc

# add git branch to prompt
curl https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim -u ~/.vimrc.bundles +BundleInstall +qa

echo "All done!"
