[package]
[package.common] # Package names common to all platforms
names = ["bat", "git", "curl", "wget", "zsh"]
[package.yay]
names = ["lazydocker", "lazygit", "neovim"]
[package.homebrew]
names = [
  "chezmoi",
  "eza",
  "fzf",
  "gnupg",
  "jless",
  "jq",
  "lazydocker",
  "lazygit",
  "neovim",
  "pinentry",
  "ssh-copy-id",
  "starship",
  "syncthing",
  "yazi",
  "zoxide",
]
[package.homebrew_cask]
names = [
  "1password-cli",
  "alfred",
  "brave-browser",
  "cursor",
  "font-jetbrains-mono",
  "ghostty",
  "localsend",
  "obsidian",
  "rocket",
  "signal",
  "slack",
  "submariner",
]
